# Generated by Django 4.0.2 on 2022-03-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
