# Generated by Django 4.0.2 on 2022-02-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='summary',
            field=models.TextField(default='Краткое описание', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
