# Generated by Django 4.0.2 on 2022-03-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_category_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='dislike',
            field=models.ManyToManyField(related_name='dislike2', to='articles.Articles'),
        ),
        migrations.AddField(
            model_name='articles',
            name='like',
            field=models.ManyToManyField(related_name='like1', to='articles.Articles'),
        ),
    ]
