# Generated by Django 4.0.2 on 2022-03-01 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_articles_dislike_articles_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='dislike',
            field=models.ManyToManyField(related_name='dislike2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articles',
            name='like',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
