# Generated by Django 4.0.2 on 2022-03-02 14:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articles_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Контент'),
        ),
    ]
