# Generated by Django 4.0.2 on 2022-03-02 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0009_comment_dislike_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
