# Generated by Django 4.0.2 on 2022-03-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_articles_content'),
        ('articles', '0010_alter_comment_dislike_alter_comment_like'),
    ]

    operations = [
    ]
