# Generated by Django 4.0.2 on 2022-03-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_merge_20220302_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='quantity_comment',
            field=models.IntegerField(default=0, verbose_name='Количество коментариев'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Заголовок'),
        ),
    ]
