# Generated by Django 4.0.2 on 2022-03-17 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_articles_title'),
        ('articles', '0012_articles_quantity_comment_alter_articles_title'),
    ]

    operations = [
    ]
