# Generated by Django 4.0.2 on 2022-03-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_merge_20220317_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='default_images/it_news_default.webp', upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
