# Generated by Django 4.0.2 on 2022-03-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_articles_for_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='for_moderation',
            field=models.BooleanField(default=False, verbose_name='На модерации'),
        ),
    ]
