# Generated by Django 4.0.2 on 2022-03-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_articles_for_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='for_moderation',
            field=models.CharField(blank=True, choices=[('moderation', 'На модерации'), ('error_moderation', 'Не прошедший модерацию'), ('not_moderation', 'Не на модерации')], default='not_moderation', max_length=100, null=True),
        ),
    ]
