# Generated by Django 4.0.2 on 2022-03-27 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0017_alter_articles_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMessageModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text_message', models.TextField(verbose_name='Текст сообщения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='message_moderation',
            field=models.ManyToManyField(blank=True, to='articles.ErrorMessageModeration', verbose_name='Сообщения от модератора'),
        ),
    ]
