# Generated by Django 4.0.2 on 2022-03-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_errormessagemoderation_articles_message_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='errormessagemoderation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активные'),
        ),
    ]
